[build]
  base = "/" 
  command = "cd client && npm install && npm run build" # Navigate to client directory and build
  publish = "client/dist" # Or whatever your build output directory is
  functions = "client/netlify/functions"

[context.production]
  command = "cd client && npm install && npm run build:prod"

[context.deploy-preview]
  command = "cd client && npm install && npm run build:preview"

[build.environment]
  NODE_VERSION = "18" 
  NPM_FLAGS = "--no-optional" 
