[build]
  base = "/" 
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "client/netlify/functions"

[context.production]
  command = "cd client && npm install && npm run build:prod"

[context.deploy-preview]
  command = "cd client && npm install && npm run build:preview"

[build.environment]
  NODE_VERSION = "20" 
  NPM_FLAGS = "--no-optional"
