import Header from "@/components/Header";
import { useState, useMemo } from "react";
import { getMessages } from "@/api/message";
import { useQuery } from "@tanstack/react-query";
import formatDate from "@/utils/formatDate";
import { Button } from "@/components/ui/button";
import { GrPowerReset } from "react-icons/gr";
import DataTable from "@/components/DataTable";
import columns from "@/components/columns/MessageReport";
import Loading from "@/components/Loading";
import { LuDownload } from "react-icons/lu";
import jsPDF from "jspdf";
import "jspdf-autotable";
import PdfPreviewModal from "./PdfPreviewModal";
import { vectorUrl, logoUrl, tagline } from "./info.js";
import { loggedInUser } from "@/api/auth";
import { Input } from "@/components/ui/input";

const MessageReport = () => {
  const [filters, setFilters] = useState([]);
  const [globalFilter, setGlobalFilter] = useState("");
  const [reset, setReset] = useState(false);
  const [pdfPreviewUrl, setPdfPreviewUrl] = useState(null);
  const [fromDate, setFromDate] = useState(""); // New state for From date
  const [toDate, setToDate] = useState(""); // New state for To date

  const { data } = useQuery({
    queryKey: ["user"],
    queryFn: loggedInUser,
    refetchOnWindowFocus: false,
  });

  const { data: allMessages, isLoading, error } = useQuery({
    queryKey: ["messages"],
    queryFn: getMessages,
    refetchOnWindowFocus: false,
  });

  if (error) {
    console.error("Error fetching activity logs:", error);
  }

  const filteredMessages = useMemo(() => {
    if (!allMessages) return [];

    return allMessages.filter((message) => {
      const matchesFilters = filters.every((filter) => {
        if (filter.value === "") return true;
        const messageValue = message[filter.id];
        return messageValue && messageValue.toLowerCase() === filter.value.toLowerCase();
      });

      const messageDate = new Date(message.date_added);
      const from = fromDate ? new Date(fromDate) : null;
      const to = toDate ? new Date(toDate) : null;

      const matchesDateRange =
        (!from || messageDate >= from) &&
        (!to || messageDate <= to);

      return matchesFilters && matchesDateRange;
    });
  }, [allMessages, filters, fromDate, toDate]);

  const handleReset = () => {
    setFilters([]);
    setGlobalFilter("");
    setReset(!reset);
    setFromDate(""); // Clear From Date
    setToDate(""); // Clear To Date
  };

  const handleGeneratePDF = (preview = false) => {
    if (!filteredMessages || filteredMessages.length === 0) {
      alert("No data available to generate PDF.");
      return;
    }

    const doc = new jsPDF({ orientation: "landscape" });
    const today = new Date().toLocaleDateString("en-US");

    
    const imgWidth = 12; 
    const imgHeight = 12;

    const addHeader = () => {
      doc.addImage(logoUrl, "PNG", 13, 22, 12, 12.5);
      doc.addImage(tagline, "PNG", 40, 22, 67, 13.5);
      doc.addImage(vectorUrl, "PNG", 26, 22, imgWidth, imgHeight);

    doc.setLineWidth(0.1);
    doc.line(14, 37, 285, 37);
    
    doc.setLineWidth(0.1);
    doc.line(14, 36.3, 285, 36.3);


    const pageWidth = doc.internal.pageSize.width; // Get the width of the page

// Text 1: "Showing result of:"
doc.setFontSize(10);
doc.setFont("helvetica", "italic");
doc.setTextColor(0, 0, 0);
doc.text("Showing result of:", 243 + imgWidth + 0, 23);

// Text 2: "Generated By: ${data.firstname} ${data.lastname}"
const text2 = `Generated By: ${data.firstname} ${data.lastname}`;
const textWidth2 = doc.getStringUnitWidth(text2) * doc.internal.getFontSize() / doc.internal.scaleFactor;
const xPos2 = pageWidth - textWidth2 - 14; // 10 is for padding from the right edge

doc.setFontSize(10);
doc.setFont("helvetica", "italic");
doc.setTextColor(0, 0, 0);
doc.text(text2, xPos2, 28);

// Text 3: "Date Range: ${fromDate || today} - ${toDate || today}"
const text3 = `Date from: ${fromDate || today} - ${toDate || today}`;
const textWidth3 = doc.getStringUnitWidth(text3) * doc.internal.getFontSize() / doc.internal.scaleFactor;
const xPos3 = pageWidth - textWidth3 - 14; // 10 is for padding from the right edge

doc.setFontSize(10);
doc.setFont("helvetica", "italic");
doc.setTextColor(0, 0, 0);
doc.text(text3, xPos3, 33);
    
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text("GUIDEURSELF", 107.5 + imgWidth + 10, 45);
        
        doc.setFontSize(13);    
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0, 0, 0);
        doc.text("User Response Report", 101   + imgWidth + 10, 50);


    };

    const addFooter = (pageNumber) => {
      doc.line(14, 195, 285, 195);
      doc.setFontSize(10).setFont("helvetica", "normal").setTextColor(100);
      doc.text(``, 140, 200);
      doc.text(`Page ${pageNumber} | Generated on: ${today}`, 232, 200);
      doc.text(`CONFIDENTIAL - For internal use only`, 14, 200);
    };

    addHeader();

    const tableData = filteredMessages.map((message) => [
        message.content,
        message.is_helpful
         ? "Yes" : "No",
        formatDate(message.date_added),
    ]);

    const rowsPerPage = 3;
    const totalPages = Math.ceil(tableData.length / rowsPerPage);

    for (let i = 0; i < totalPages; i++) {
      if (i > 0) {
        doc.addPage();
        addHeader();
      }

      const chunk = tableData.slice(i * rowsPerPage, (i + 1) * rowsPerPage);
      doc.autoTable({
        head: [["MESSAGE", "HELPFUL", "DATE CREATED"]],
        body: chunk,
        startY: 55,
        didDrawPage: () => addFooter(doc.internal.getNumberOfPages()),

        styles: { // Center the text in cells
          valign: 'middle', // Vertical alignment (optional)
          lineWidth: 0.2, // Border line width
          lineColor: [0, 0, 0], // Black border
        },
        headStyles: {
          halign: 'center', // Center the header text
          fontSize: 9,
          fontStyle: 'bold',
          textColor: [0, 0, 0], 
          fillColor: [222, 234, 246],
        }, 
        bodyStyles: {
          fillColor: [255, 255, 255], // Set body rows background color to white (RGB)
        },
        tableWidth: 'auto',
      });
    }

    if (preview) {
      const pdfBlob = doc.output("blob");
      const pdfUrl = URL.createObjectURL(pdfBlob);
      
      window.open(pdfUrl, '_blank');
    } else {
      doc.save("messages_report.pdf");
    }
  };

  return (
    <div className="flex flex-1 flex-col gap-5">
      <Header title="Response Review Report" subtitle="Access, monitor, and generate reports on user response review" />

      <div className="flex flex-col gap-5">
        <div className="flex items-center gap-5">
          <p>Filters:</p>
          <Input type="date" className="w-[170px]" value={fromDate} onChange={(e) => setFromDate(e.target.value)} />
          <Input type="date" className="w-[170px]" value={toDate} onChange={(e) => setToDate(e.target.value)} />
          <Button className="text-secondary-100-75" variant="outline" onClick={handleReset}>
            <GrPowerReset /> Reset Filters
          </Button>
          <div className="ml-auto space-x-5">
            <Button variant="ghost" className="text-base-200" onClick={() => handleGeneratePDF(true)}>File Preview</Button>
            <Button className="border border-base-200 bg-base-200/10 text-base-200 hover:bg-base-200 hover:text-white" onClick={() => handleGeneratePDF(false)}>
              <LuDownload /> Download
            </Button>
          </div>
        </div>
      </div>

      {isLoading ? <Loading /> 
      : <DataTable 
      data={filteredMessages} 
      columns={() => columns({ truncateResponse: true })}
      filters={filters} 
      setFilters={setFilters} 
      pageSize={11} 
      globalFilter={globalFilter} 
      setGlobalFilter={setGlobalFilter} 
      />}

      {pdfPreviewUrl && <PdfPreviewModal pdfUrl={pdfPreviewUrl} onClose={() => setPdfPreviewUrl(null)} />}
    </div>
  );
};

export default MessageReport;
